# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc21a2eb29df578a8d2005df08aa67286c8bc7b7090e7db577398af2ad920c995ab97f5c0d8dc4c21f639ad11a947e1e7107fd5383ebd6367b1b9c5cf0c72855

test:
  secret_key_base: 62a8d276736fd836c618b971bb8cbd775ab56343f4d24da71f4a9bea10c257bb413478e9053a6cef07426db16de23aac93602b4849aeafa646aeba3169d9207e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
